declare const VITE_DEVELOPMENT_MODE: string

declare const VITE_MORALIS_APP_ID: string
declare const VITE_MORALIS_MASTER_KEY: string
declare const VITE_CURRENCY_CONTRACT: string
declare const VITE_OWNER: string

declare const VITE_MORALIS_API_KEY_PROD: string
declare const VITE_MORALIS_SERVER_URL_PROD: string
declare const VITE_ALCHEMY_PRIVATE_API_KEY_PROD: string
declare const VITE_ALCHEMY_URL_PROVIDER_PROD: string
declare const VITE_STRIPE_PUBLIC_KEY_PROD: string
declare const VITE_STRIPE_PRIVATE_KEY_PROD: string
declare const VITE_STRIPE_PRODUCT_KNRT_PROD: string
declare const VITE_STRIPE_PRODUCT_MATIC_PROD: string
declare const VITE_STRIPE_PRODUCT_KNRT_TEST_CNRT_PROD: string
declare const VITE_CHAIN_ID_MAINNET_PROD: string
declare const VITE_TOKEN_ERC20_PROD: string
declare const VITE_TOKEN_ERC721_AUCTION_PROD: string
declare const VITE_TOKEN_ERC721_COLLECTION_PROD: string
declare const VITE_CURRENCY_PRICE_CONTRACT_PROD: string
declare const VITE_BLOCK_EXPLORER_URL_PROD: string
declare const VITE_NAME_TOKEN_PROD: string

declare const VITE_MORALIS_APP_ID_DEV: string
declare const VITE_MORALIS_MASTER_KEY_DEV: string
declare const VITE_MORALIS_API_KEY_DEV: string
declare const VITE_MORALIS_SERVER_URL_DEV: string
declare const VITE_ALCHEMY_PRIVATE_API_KEY_DEV: string
declare const VITE_ALCHEMY_URL_PROVIDER_DEV: string
declare const VITE_STRIPE_PUBLIC_KEY_DEV: string
declare const VITE_STRIPE_PRIVATE_KEY_DEV: string
declare const VITE_STRIPE_PRODUCT_KNRT_DEV: string
declare const VITE_STRIPE_PRODUCT_MATIC_DEV: string
declare const VITE_STRIPE_PRODUCT_KNRT_TEST_CNRT_DEV: string
declare const VITE_CHAIN_ID_MAINNET_DEV: string
declare const VITE_CHAIN_ID_TESTNET_DEV: string
declare const VITE_TOKEN_ERC20_DEV: string
declare const VITE_TOKEN_ERC721_AUCTION_DEV: string
declare const VITE_TOKEN_ERC721_COLLECTION_DEV: string
declare const VITE_CURRENCY_PRICE_CONTRACT_DEV: string
declare const VITE_BLOCK_EXPLORER_URL_DEV: string
declare const VITE_NAME_TOKEN_DEV: string
