export const footerData = {
  logo: {
    src: '/logo.svg',
    alt: 'logo',
  },
  socialMedia: [
    {
      id: 1,
      src: 'https://cdn-useast1.kapwing.com/static/twitter-footer-light.webp',
      alt: 'Twitter',
    },
    {
      id: 2,
      src: 'https://cdn-useast1.kapwing.com/static/yt-footer-light.webp',
      alt: 'Youtube',
    },
    {
      id: 3,
      src: 'https://cdn-useast1.kapwing.com/static/ig-footer-light.webp',
      alt: 'Instagram',
    },
    {
      id: 4,
      src: 'https://cdn-useast1.kapwing.com/static/tiktok-footer-light.webp',
      alt: 'TikTok',
    },
    {
      id: 5,
      src: 'https://cdn-useast1.kapwing.com/static/fb-footer-light.webp',
      alt: 'Facebook',
    },
  ],
  sections: [
    {
      id: 1,
      title: 'Tools',
      items: [
        { id: 1, name: 'Video Editor' },
        { id: 2, name: 'Subtitles' },
        { id: 3, name: 'Meme Generator' },
        { id: 4, name: 'Convert Video' },
        { id: 5, name: 'Video Trimmer' },
        { id: 6, name: 'Screen Recorder' },
        { id: 7, name: 'View All' },
      ],
    },
    {
      id: 2,
      title: 'AI-powered',
      items: [
        { id: 1, name: 'Smart Cut' },
        { id: 2, name: 'AI Video Generator' },
        { id: 3, name: 'Clean Audio' },
        { id: 4, name: 'AI Image Generator' },
        { id: 5, name: 'Text to Speech' },
        { id: 6, name: 'Document to Video' },
        { id: 7, name: 'View All' },
      ],
    },
    {
      id: 3,
      title: 'Templates',
      items: [
        { id: 1, name: 'Video Templates' },
        { id: 2, name: 'Meme Templates' },
        { id: 3, name: 'Collage Templates' },
        { id: 4, name: 'Instagram Video' },
        { id: 5, name: 'Popular Templates' },
        { id: 6, name: 'EDU Templates' },
        { id: 7, name: 'View All' },
      ],
    },
    {
      id: 4,
      title: 'Learn',
      items: [
        { id: 1, name: 'About Us' },
        { id: 2, name: 'Resources' },
        { id: 3, name: 'Help Center' },
        { id: 4, name: 'Blog' },
        { id: 5, name: 'EDU' },
        { id: 6, name: 'Create' },
        { id: 7, name: 'Explore' },
        { id: 8, name: 'Teams' },
        { id: 9, name: 'Contact Us' },
      ],
    },
    {
      id: 5,
      title: 'Company',
      items: [
        { id: 1, name: 'Pricing' },
        { id: 2, name: 'Careers' },
        { id: 3, name: 'Partnerships' },
        { id: 4, name: 'Affiliates' },
        { id: 5, name: 'Plugins' },
        { id: 6, name: 'Release Notes' },
        { id: 7, name: 'Creators Fund' },
        { id: 8, name: 'Refund Policy' },
        { id: 9, name: 'Privacy Policy' },
        { id: 10, name: 'Terms of Service' },
      ],
    },
  ],
  languages: [
    { id: 1, name: 'English' },
    { id: 2, name: 'Español' },
    { id: 3, name: 'Français' },
    { id: 4, name: 'Português' },
    { id: 5, name: '日本' },
    { id: 6, name: 'عربي' },
  ],
  copyright: '© 2024 Kapwing. Made with love in San Francisco, California.',
}
